### ISSUE TITLE
explicit entrypoint required?

### ISSUE THREAD

**Issue by goern** [RHsyseng/docker-rhel-sonarqube#3]
Why do you do https://github.com/RHsyseng/docker-rhel-sonarqube/blob/master/sonarqube-template.yaml#L154 ? Aint that entrypoint defined by https://github.com/RHsyseng/docker-rhel-sonarqube/blob/master/Dockerfile#L89 ?

**Comment by tchughesiv** [comment]
i believe that was added by ocp when i did an export to create the template... unnecessary though, we can remove.
