### ISSUE TITLE
Provide a CentOS version

### ISSUE THREAD

**Issue by luebken** [RHsyseng/docker-rhel-sonarqube#8]
There is this pattern of providing both a RHEL based and a CentOS based version of an OpenShift template. This helps OpenSource adoption and also advertises Red Hat supported images.

Thoughts? 

Note @goern has a CentOS version: https://github.com/goern/docker-rhel-sonarqube/tree/centos7

ping @goern @tchughesiv

**Comment by luebken** [comment]
ping @kbsingh

**Comment by tchughesiv** [comment]
agree... is a centos7 branch the preferred approach?  I think i like that model

**Comment by kbsingh** [comment]
would certainly help spread things a bit

**Comment by tchughesiv** [comment]
resolved by https://github.com/RHsyseng/docker-rhel-sonarqube/pull/10
demo for now w/ ```oc new-app tchughesiv/sonarqube-centos```
